spring.application.name=swiftchat
server.port=8081

spring.data.redis.host=redis-17366.c283.us-east-1-4.ec2.cloud.redislabs.com
spring.data.redis.port=17366
spring.data.redis.username=default
spring.data.redis.password=dJWyDGotjUV2ZZqvMW5RqFCjqrh3UBWO

spring.redis.ssl.enabled=true